INSERT INTO movie(title, year, genre, duration, director)
VALUES ('The Internship', 2013, 'COMEDY', 119, 'Shawn Levy'),
       ('The Silence of the Lambs', 1990, 'THRILLER', 118, 'Jonathan Demme'),
       ('Ghost', 1990, 'ROMANCE', 127, 'Jerry Zucker'),
       ('What Happens in Vegas', 2008, 'ROMANCE', 99, 'Shawn Levy'),
       ('Deadpool', 2016, 'FANTASY', 108, 'Tim Miller'),
       ('Deadpool 2', 2018, 'FANTASY', 119, 'David Leitch'),
       ('The Notebook', 2004, 'DRAMA', 124, 'Nick Cassavetes'),
       ('The Naked Gun: From the Files of Police Squad!', 1988, 'COMEDY', 85, 'David Zucker'),
       ('The Road', 2009, 'DRAMA', 111, 'John Hillcoat'),
       ('Inglourious Basterds', 2009, 'ACTION', 153, 'Quentin Tarantino'),
       ('Once Upon a Time in... Hollywood', 2019, 'DRAMA', 161, 'Quentin Tarantino'),
       ('Phone Booth', 2002, 'THRILLER', 81, 'Joel Schumacher'),
       ('Batman', 1989, 'FANTASY', 126, 'Tim Burton'),
       ('Sin City', 2005, 'ACTION', 124, 'Quentin Tarantino'),
       ('Batman Begins', 2005, 'FANTASY', 140, 'Christopher Nolan'),
       ('Sleepy Hollow', 1999, 'THRILLER', 105, 'Tim Burton'),
       ('The Batman', 2022, 'FANTASY', 176, 'Matt Reeves'),
       ('Inception', 2010, 'FANTASY', 148, 'Christopher Nolan'),
       ('Django Unchained', 2012, 'WESTERN', 165, 'Quentin Tarantino'),
       ('From Hell', 2001, 'HORROR', 122, 'Albert Hughes'),
       ('Meet Joe Black', 1998, 'MYSTERY', 178, 'Martin Brest')